# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284aa5944bf7aeb77147eb742c34381dcea95ab48c7477e5df22cb71c589cdd1eb242534e639d5f7114a74dca5d41c9a342e99f26311de440f416bf864b12a2d

test:
  secret_key_base: a46b820c3fb8b2c46872e34094eae04e79d9b757d4b48bbe9448d708cd20c0f271b32216ea745ab2f6292950c8fee37ecca6319b100dd8d1571c64dd21edc4a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
